### PR TITLE
Handle empty extension artifact parsing

### LINKED ISSUE #329: Unable to use linux executable as plugin without extension, due to default extension being 'exe'.
Hi all,

I am trying to use an executable as a plugin which is imported via artifact.
Helpfully there is a osdetector so the correct binary can be selected for windows/linux.

However the default extension that is provided is 'exe'.
[ToolsLocator.groovy](https://github.com/google/protobuf-gradle-plugin/blob/74997dceac6eef0095826067a32f24f11b2c051d/src/main/groovy/com/google/protobuf/gradle/ToolsLocator.groovy#L102)
```groovy
    Map<String, String> notation = [
            group:groupId,
            name:artifact,
            version:version,
            classifier:classifier ?: project.osdetector.classifier,
            ext:extension ?: 'exe',
    ]
```
Linux executables commonly don't have extensions, so when trying to load an artifact with no extension, this always gets defaulted to exe, hence the fetching fails on linux.
For example, this in a build script will still result in exe:
```groovy
ext {
    architecture = project.osdetector.classifier
    executableExtension = architecture == "windows-x86_64" ? "exe": ""
}
protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.9.1'
    }
    plugins {
        doc {
            artifact = "com.company:useful-library:0.1.0:$architecture@$executableExtension"
        }
    }
}
```

Workarounds to this issue:
- Require that artifactory executables have 'exe' extensions
  - This doesn't seem ideal as they aren't windows executables.
- Use the 'elf' extension for linux executables.
  - This seems better, however use of elf is quite often rare.

However both of these options require the artifactory images to be in a certain format, there is no way for someone wishing to use a linux executable, from a repository out of their control, when there is no extension on the linux executable.

How would you feel about removing the default extension, so:
```groovy
    Map<String, String> notation = [
            group:groupId,
            name:artifact,
            version:version,
            classifier:classifier ?: project.osdetector.classifier,
            ext:extension ?: null,
    ]
```

### PR DESCRIPTION
**Pull request by voidzcy**
Resolves #329

### CODE REVIEW

File: src/main/groovy/com/google/protobuf/gradle/ToolsLocator.groovy [hunk 1]
```diff
@@ -51,7 +51,12 @@ class ToolsLocator {
     String version
     String classifier
 
-    (artifact, extension) = artifactCoordinate.tokenize('@')
+    if (artifactCoordinate.endsWith('@')) {
+      artifact = artifactCoordinate[0..-2]
+      extension = ''
+    } else {
+      (artifact, extension) = artifactCoordinate.tokenize('@')
```
Comment (zhangkun83) [inline src/main/groovy/com/google/protobuf/gradle/ToolsLocator.groovy]: nit: could it simpler:
```groovy
(artifact, extension) = artifactCoordinate.tokenize('@')
if (extension == null && artifactCoordinate.endsWith('@')) {
  extension == ''
}
```

Comment (voidzcy) [reply src/main/groovy/com/google/protobuf/gradle/ToolsLocator.groovy]: Sure.
