### PR TITLE
Make generateProtoTask resolve file/directory lazily to allow including build time proto

### LINKED ISSUE #313: Cannot find build-time generated proto files
I have an issue, and struggling with for a few days:
  protoc: stdout: . stderr C:\Users\myuser\myWorkspace\mainProject\mySubProject\build\out\path\to\proto\protofile.proto : File does not reside within any path specified using --proto_path (or -I).  You must specify...
I have checked the forumns but non of them helped.

I have used the gradle plugin in a java project, dependency verisons:

Classpath dependency:
"com.google.protobuf:protobuf-gradle-plugin:0.8.8"

Dependencies:
"com.google.protobuf:protoc:3.3.0"
"com.google.protobuf:protobuf-java:3.4.0"

Artifacts
"io.grpc:protoc-gen-grpc-java:1.17.1"
"com.google.protobuf:protoc:3.3.0"

apply plugin: 'com.google.protobuf'

I have used absolute path on proto{srcDir "${rootDir.getAbsolutePath()}/mySubProj/build/out"}

Our scenario would be the following
1, create proto with my tasks
2, From proto generate java classas - We have the issue here with protobuf

I have set the dependency of generation files to proto with the following code:

            if (task.name.equals("generateProto")) {
               //prepare files is for creating proto files
                prepareFiles.each {
                    task.dependsOn(it)
                }
            }

Also I have tried to separate protobuf to a submodule within the project and se tthe project dependencies, but I had the same error:

 protoc: stdout: . stderr C:\Users\myuser\myWorkspace\mainProject\mySubProject\build\out\path\to\proto\protofile.proto : File does not reside within any path specified using --proto_path (or -I). You must specify

There are a couple of interesting things about this error. 

0, I have checked the execution order of tasks, and proto files present when generateProto task starts. I was checked it numerous way and my tasks are getting executed before generateProto.
1, I have just given the path for ${rootDir.getAbsolutePath()}/mySubProj/build/out and the error message it exactly points to the existing file.
2, If i run the build/task one more time, it succeeds.
3, If I run the tasks manually, createProto then the generate proto it succeeds .

Any idea how can I resolve the issue? Our goal would be to during buildtime execute the following tasks 
1. create protofiles 
2. proto to java conversion(with protobuf)
 
It would happen during the build time.

### PR DESCRIPTION
**Pull request by voidzcy**
Resolves #313

### CODE REVIEW

File: src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy [hunk 1]
```diff
@@ -454,7 +454,9 @@ public class GenerateProtoTask extends DefaultTask {
       outputDir.mkdirs()
     }
 
-    List<String> dirs = includeDirs*.path.collect { "-I${it}" }
+    // The source directory designated from sourceSet may not actually exist on disk.
+    // "include" it only when it exists, so that Gradle and protoc won't complain.
+    List<String> dirs = includeDirs.filter { it.exists() }*.path.collect { "-I${it}" }
```
Comment (zhangkun83) [inline src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy]: Also check `isDirectory()`?

File: src/main/groovy/com/google/protobuf/gradle/ProtobufExtract.groovy [hunk 2]
```diff
@@ -109,11 +110,11 @@ class ProtobufExtract extends DefaultTask {
...
     Preconditions.checkState(this.destDir == null, 'destDir already set')
-    this.destDir = destDir
-    outputs.dir destDir
+    this.destDir = project.files(destDir)
+    outputs.dirs(this.destDir)
   }
 
   protected File getDestDir() {
-    return destDir
+    return destDir.getSingleFile()
```
Comment (zhangkun83) [inline src/main/groovy/com/google/protobuf/gradle/ProtobufExtract.groovy]: The changes in this file doesn't seem necessary.

Comment (voidzcy) [reply src/main/groovy/com/google/protobuf/gradle/ProtobufExtract.groovy]: Yes, you are right.

File: src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy (hunk 1 above)
Comment (zhangkun83) [reply src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy]: It's unclear to me whether `ConfigurableFileCollection` adds files recursively or not. Documentation is very vague on this, which is why I didn't use it in the first place. It seems the effective change is moving `exists()` check down to here. Wouldn't it also work if you kept `includeDirs` as a `List<File>`?

File: src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy [hunk 3]
```diff
@@ -331,18 +331,18 @@ public class GenerateProtoTask extends DefaultTask {
...
    */
-  public void addIncludeDir(File dir) {
+  public void addIncludeDir(FileCollection dir) {
     checkCanConfig()
-    includeDirs.add(dir)
+    includeDirs.from(dir)
     // Register all files under the directory as input so that Gradle will check their changes for
     // incremental build
-    inputs.dir(dir).withPathSensitivity(PathSensitivity.RELATIVE)
+    inputs.files(dir).withPathSensitivity(PathSensitivity.RELATIVE)
```
Comment (zhangkun83) [inline src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy]: What's the difference between `files()` and `dir()`?

File: src/main/groovy/com/google/protobuf/gradle/ProtobufExtract.groovy [hunk 4]
```diff
@@ -110,7 +110,7 @@ class ProtobufExtract extends DefaultTask {
   protected void setDestDir(File destDir) {
     Preconditions.checkState(this.destDir == null, 'destDir already set')
     this.destDir = destDir
-    outputs.dir destDir
+    outputs.dirs destDir
```
Comment (zhangkun83) [inline src/main/groovy/com/google/protobuf/gradle/ProtobufExtract.groovy]: The difference between `dir()` and `dirs()` are the number of arguments they can take. Since you have only one arguments here, it doesn't seem this change is necessary.

File: src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy (hunk 1 above)
Comment (voidzcy) [reply src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy]: Since we the issue we are trying to solve is the problem that some directory in the "proto" `SourceDirectorySet` does not exist in configuration phase 

(e.g., 
```
main {
        proto {
            srcDir "${buildDir}/proto"
        }
    }
```
), so we cannot refer to directories of "proto" `SourceDirectorySet` like https://github.com/google/protobuf-gradle-plugin/blob/d25369e20db8a3b3520c3835523641b5e1321ee1/src/main/groovy/com/google/protobuf/gradle/ProtobufPlugin.groovy#L317 as Gradle will try to resolve that path and will fail. Instead, we need to use lazy type such as `FileCollection`.

From [`SourceDirectorySet#getSourceDirectories`](https://docs.gradle.org/current/javadoc/org/gradle/api/file/SourceDirectorySet.html#getSourceDirectories--):
> The returned collection is live and reflects changes to this source directory set.

This is the whole point for using `ConfigurableFileCollection `.

I don't think `ConfigurableFileCollection#from` adds files recursively as the [doc](https://docs.gradle.org/current/javadoc/org/gradle/api/file/ConfigurableFileCollection.html#from-java.lang.Object...-) says it just adds paths converted to `ConfigurableFileCollection` by `Project#files` for the given paths and nothing else. `Project#files` only returns a `ConfigurableFileCollection` representation of the given paths and does not expand them.

File: src/main/groovy/com/google/protobuf/gradle/ProtobufExtract.groovy (hunk 4 above)
Comment (voidzcy) [reply src/main/groovy/com/google/protobuf/gradle/ProtobufExtract.groovy]: Oops. This is a typo (although functionally they have no difference).

File: src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy (hunk 3 above)
Comment (voidzcy) [reply src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy]: I believe `inputs.files(includeDirs)` would be the correct one as there could be more than one included directories and any of them changes should trigger the task to run. The documentation is vague and does not mention if calling `inputs.dir()` or `input.file()` multiple times would additively register them as task input or will just replace existing registered one. So `inputs.files(includeDirs)` would be better.

Comment (zhangkun83) [reply src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy]: `TaskInputs.files()` is unnecessary at least because there is one argument. `TaskInputs.file()`'s doc says it registers one ("some") file, and "The given path is evaluated as per Project.file(Object).". If that "file" is a directory, which is the case here, from our discussion around `FileCollection` (vs `File`) below, it won't be expanded. In contrast, `TaskInputs.dir()` specifically says "All files found under the given directory are treated as input files for this task."

RE: replacing vs addition, all methods in question uses the same verb "Register", which I think implies addition. Even if it did mean "replacing", `files()` and `dir()` should be the same in this aspect.

Comment (voidzcy) [reply src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy]: Fair, changed back to `TaskInputs.dir()`.

Comment (voidzcy) [reply src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy]: It turns out we cannot use `TaskInputs.file()` or `TaskInputs.dir()` here. As it says, "The given path is evaluated as per Project.file(Object)" for `TaskInputs.file()` and and `TaskInputs.dir()`. This means the actual path (which may not exist) will be resolved as mentioned in [Project.file()](https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#file-java.lang.Object-). If use `TaskInputs.dir()`, we will encounter the same issue as #253 since we are including a non-existing directory in `GenerateProtoTask`'s task inputs.

`.files()` is not only for providing multiple files, but also returns `FileCollection` type, which represents file/directory with a higher abstraction. Since Gradle explicitly resolves the given path for `TaskInputs.file()` and `TaskInputs.dir()`, it provides them as separate APIs for file and directory, and they can only be called on file and directory respectively (otherwise, error). That's the reason, but have nothing to do with whether a directory will be expanded or not. In abstraction, a _directory_ is also a file and anything changing in that directory implies the _directory_ has changed. What "All files found under the given directory are treated as input files for this task" means, I believe, is anything under the given directory is part of task inputs, recursively. Isn't that what we want?

I don't see any problem using registering `FileCollection` as task inputs here, as long as the concern for whether "register" is additive or replacing is clear.

File: src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy (hunk 1 above)
Comment (voidzcy) [reply src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy]: What matters is whether everything under the given directory is treated as the inputs. i.e., anything (under the given directory recursively) changing is treated as the given directory has changed. But `File` and `FileCollection` are just different datatypes for representing a directory. Its name containing "Collection" just means we can represent >= 1 file/directories in a single object but not "create a collection, add each individual files in given directory, return the collection". You can play with `FileCollection#getSingleFile()` or `FileCollection#getFiles()` to confirm this.

File: src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy (hunk 3 above)
Comment (voidzcy) [reply src/main/groovy/com/google/protobuf/gradle/GenerateProtoTask.groovy]: I experimented with `TaskInputs.files()` with a single directory path as the input. Gradle is able to detect any changes inside that directory recursively (not just the immediate child of the directory). So I believe using `TaskInputs.files()` for a directory achieves the goal of "Register all files under the directory as input so that Gradle will check their changes for incremental build", which is what we want `TaskInputs.dir()` to do. 
- Seems Gradle has some more advanced ["fingerprint"](https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:how_does_it_work) technique to detect task inputs changes, instead of simply based on last-modified-timestamp in Unix. So this can detect changes recursively in a directory tree.

I also verified that `FileCollection` does not expand directory structures if it contains a directory, it's just a set of original files/directories as we give it in.

Also, `TaskInputs.file()`, `TaskInputs.files()` and `TaskInputs.dir()` does register task inputs additively.
